// src/lib/coachShare.js
// Supabase helpers for the Coach Share feature.
// All mutations require the authenticated user; read via token uses anon key.

import { supabase } from './supabase';

/** Fetch the current user's coach_share record (or null). */
export async function getCoachShare(userId) {
  if (!supabase || !userId) return null;
  const { data, error } = await supabase
    .from('coach_shares')
    .select('*')
    .eq('user_id', userId)
    .maybeSingle();
  if (error) throw error;
  return data;
}

/**
 * Enable coach sharing for the current user.
 * Upserts a record — if one exists it stays (keeps the existing token).
 * Returns the coach_share row.
 */
export async function enableCoachShare(userId) {
  if (!supabase || !userId) throw new Error('Supabase not configured');

  // Check if a record already exists
  const existing = await getCoachShare(userId);
  if (existing) {
    // Just mark enabled
    const { data, error } = await supabase
      .from('coach_shares')
      .update({ enabled: true })
      .eq('user_id', userId)
      .select()
      .single();
    if (error) throw error;
    return data;
  }

  // Insert a new record — token is generated by Supabase default (gen_random_uuid())
  const { data, error } = await supabase
    .from('coach_shares')
    .insert({ user_id: userId, enabled: true })
    .select()
    .single();
  if (error) throw error;
  return data;
}

/** Disable coach sharing (keeps record, sets enabled=false). */
export async function disableCoachShare(userId) {
  if (!supabase || !userId) throw new Error('Supabase not configured');
  const { data, error } = await supabase
    .from('coach_shares')
    .update({ enabled: false })
    .eq('user_id', userId)
    .select()
    .single();
  if (error) throw error;
  return data;
}

/**
 * Rotate the share token: delete the existing record and insert a fresh one.
 * This revokes access for anyone who had the old link.
 */
export async function rotateCoachToken(userId) {
  if (!supabase || !userId) throw new Error('Supabase not configured');

  // Delete existing
  await supabase.from('coach_shares').delete().eq('user_id', userId);

  // Insert fresh — Supabase generates a new UUID token
  const { data, error } = await supabase
    .from('coach_shares')
    .insert({ user_id: userId, enabled: true, rotated_at: new Date().toISOString() })
    .select()
    .single();
  if (error) throw error;
  return data;
}

/**
 * Fetch coach dashboard data for a given share token.
 * Uses the SECURITY DEFINER RPC — works without authentication.
 * Returns null when the token is invalid or sharing is disabled.
 */
export async function getCoachData(token) {
  if (!supabase) throw new Error('Supabase not configured');
  const { data, error } = await supabase.rpc('get_coach_data', { p_token: token });
  if (error) throw error;
  return data; // null when token invalid/disabled
}
